fix(build): fix initial build args
flipperzero-rs/flipperzero-template pull request #6
Opened 2024-08-08 11:54 UTC by MassivDash

2024-08-08 12:01 UTC, MassivDash commented
Fix for issue https://github.com/flipperzero-rs/flipperzero-template/issues/5

2024-08-08 15:24 UTC, JarvisCraft requested changes

2024-08-08 15:24 UTC, JarvisCraft commented on .gitignore
> +cargo.lock
```suggestion
Cargo.lock
```

2024-08-09 08:10 UTC, JarvisCraft commented
Thanks for your contribution!

Just a small fix above (since `.gitignore` is case sensitive), but this looks good to me :)

2024-08-09 11:11 UTC, JarvisCraft approved these changes

2024-08-09 11:11 UTC, merged

2024-08-09 11:11 UTC, JarvisCraft commented
Thanks for the fix!